SW-180: ECS Cluster Cloudformation Template
govuk-one-login/central-sre-security-hub-cfn pull request #38
Opened 2024-04-08 11:37 UTC by NanaAkua28

2024-04-09 09:25 UTC, melvabout requested changes
There are checkov fixes required as per the build failure. Probably Security hub fixes too.

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +    UpdateReplacePolicy: Delete
UpdateReplacePolicy and DeletionPolicy should be parameterised. Also look at what resources these can be applied to.

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +  DestinationArn:
Can this have a more descriptive name Like `CentralisedLogsDestinationArn` or `LoggingDestinationArn`

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +        - PolicyName: !Sub "${AWS::StackName}-ECSTaskExecutionPolicy" # come back to this
`# come back to this`? Do need some help with this?

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +    UpdateReplacePolicy: Delete
Same as above parameterised

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +    # DependsOn: # DependsOn fails when condition is set on the resource it depends on
Does it need both the condition and the depends on? Not sure on execution order, put the condition before the depends on in case it is a s simple as that.

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +    # DependsOn: CloudFrontLogsBucket - cannot depend on a bucket for which a resource has not been created
This can go we get `LoggingBucket` passed in as a parameter

2024-04-09 09:25 UTC, melvabout commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +    Export:
Don't need the exports. You can fetch the outputs from on service catalog provisioned product and pass them in as inputs to the next. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-cloudformationprovisionedproduct.html#aws-resource-servicecatalog-cloudformationprovisionedproduct--examples

2024-04-09 11:07 UTC, NanaAkua28 commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +    # DependsOn: # DependsOn fails when condition is set on the resource it depends on
It was as simple as putting the condition before the depends on, haha

2024-04-09 11:12 UTC, NanaAkua28 commented on service_catalog_portfolios/storage/ecs/ecs-cluster.yaml
> +  IfUseFargateSpot: !Equals [!Ref UseFargateSpot, "Yes"]
Would the same style apply for the  `IsNotDevelopment:` condition?

2024-06-04 12:01 UTC, dangital approved these changes

2024-06-04 12:01 UTC, merged